name: OpsChain Context
description: Setup OpsChain Properties Context within a GitHub Action Workflow
author: 'LimePoint Pty Ltd'
branding:
  icon: 'share-2'
  color: 'green'
inputs:
      project:
        # The value of this parameter is a string specifying the data type of the input. 
        # This must be one of: boolean, choice, number, environment or string.
        type: string
        description: 'Project Code'
        required: true
      environment:
        # type: environment
        type: string
        description: 'Environment Code'
        required: false
      asset:
        type: string
        description: 'Asset Code'
        required: true
      action:
        type: string
        description: 'Action'
        required: true
      change_id:
        type: string
        description: 'OpsChain Change ID Reference'
        required: true
      commit_sha:
        type: string
        description: 'OpsChain Git Commit Sha'
        required: true
      opschain_api_url:
        type: string
        description: 'OpsChain API URL'
        required: true
      opschain_api_token:
        type: string
        description: 'OpsChain API Token'
        required: true

runs:
  using: 'node20'
  main: 'index.js'
